### PR TITLE
Laravel 10 Support

### PR DESCRIPTION
**Pull request by advil0**
This PR adds support for Laravel 10

### CODE REVIEW

**Comment by advil0** [comment]
@rennokki any chance this could be merged?  this is the only package holding me up from upgrading to Laravel 10 :)

**Comment by ricardomartos** [comment]
@rennokki  please?

**Comment by BramImhof** [comment]
Could you please merge this? Thanks for the package!

**Review by reinaldoacosta — APPROVED** [review]

**Comment by zoispag** [comment]
@rennokki can we help with something here?

**Review by Smokietr — APPROVED** [review]

**Pull request merged**
