### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/renoki-co/laravel-eloquent-query-cache/pull/120/commits/099c646ea8f6575de643cec8bf569e80eb36fb5a?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by francoism90** [comment]
Could this please be merged? :)

**Comment by rennokki** [comment]
[One of the packages](https://github.com/chelout/laravel-relationship-events) is not upgraded to Laravel 9.x yet, and I cannot merge it for now.

**Comment by francoism90** [comment]
@rennokki Is that still maintained? Hopefully it will be merged upstream soon.

**Comment by rennokki** [comment]
@francoism90 I hope it's maintained. 😨

**Comment by francoism90** [comment]
@rennokki https://github.com/chelout/laravel-relationship-events/issues/46

I don't know, seems the last bump was in 2020.

**Comment by rennokki** [comment]
@francoism90 Just created an issue: https://github.com/artificertech/laravel-relationship-events/issues/3

**Comment by rennokki** [comment]
@aneesdev Please see the previous discussion in this PR.

**Comment by aneesdev** [comment]
@rennokki seems like https://github.com/artificertech/laravel-relationship-events/pull/4 has been merged

**Comment by francoism90** [comment]
@rennokki Thanks! :)

**Pull request merged**
